version: '3.7'

services:
  db:
    image: mysql:5.7
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=secreto
      - MYSQL_DATABASE=album
      - MYSQL_USER=album
      - MYSQL_PASSWORD=secreto
    networks: ['mynetwork'] 
  backend:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    expose:
      - "8000"
    restart: always
    networks: ['mynetwork']
    hostname: backend
    depends_on:
        - db
    links:
        - db:db
  frontend:
    build: ./frontend
    volumes:
        - ./frontend:/app
        - /app/node_modules
    ports:
        - "3000:3000"
    environment:
        - NODE_ENV=development
    links:
      - backend:backend
    networks: ['mynetwork']
    command: yarn --cwd album/ start
    depends_on: 
      - backend
networks: {mynetwork: {}}